### ISSUE TITLE
Remove linha depois de adicionar uma linha

### ISSUE THREAD

**Issue by kmmelcher** [kmmelcher/plp-sad#12]
Depois de adicionar uma linha se você tentar remover a linha ela não será removida.
![image](https://user-images.githubusercontent.com/20446656/155382402-d4f399ed-f329-4c51-8652-d6b24eb2d321.png)

![image](https://user-images.githubusercontent.com/20446656/155382502-49a80db5-6da4-4922-bbcc-7cbb6bd8a147.png)

**Comment by viniciussousaazevedo** [comment]
Essa linha não será removida porque o Haskell está apenas buscando por campos que contenham "id = " + id. No caso, o que o Haskell está tentando fazer é deletar uma linha que tenha "id = test". Como não existe, ele não realiza nenhuma operação

Evidencia de funcionamento: https://drive.google.com/file/d/1VrLOEWiNxF3AaHW6ARL8tjmk0pMYf2bE/view
